--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SET search_path = public, pg_catalog;
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: appointments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.appointments (
    id bigint NOT NULL,
    date_time_end timestamp(6) without time zone,
    date_time_start timestamp(6) without time zone,
    status character varying(255),
    patient_id bigint,
    practitioner_id bigint,
    notes character varying(255),
    CONSTRAINT appointments_status_check CHECK (((status)::text = ANY ((ARRAY['SCHEDULED'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);


--
-- Name: appointments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.appointments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.appointments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.audit_logs (
    id bigint NOT NULL,
    actor_role character varying(30),
    actor_user_id bigint,
    actor_username character varying(100),
    event_type character varying(80) NOT NULL,
    http_method character varying(10),
    ip_address character varying(100),
    message character varying(300),
    occurred_at timestamp(6) without time zone NOT NULL,
    path character varying(255),
    request_id character varying(64),
    status character varying(20) NOT NULL,
    target_id character varying(120),
    target_type character varying(80),
    location character varying(120)
);


--
-- Name: audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devise_item_teeth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devise_item_teeth (
    devise_item_id bigint NOT NULL,
    teeth integer
);


--
-- Name: devise_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devise_items (
    id bigint NOT NULL,
    price double precision,
    devise_id bigint,
    prothesis_catalog_id bigint,
    treatment_catalog_id bigint,
    quantity integer,
    unit_price double precision
);


--
-- Name: devise_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devise_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devise_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: devises; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.devises (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    status character varying(255),
    total_amount double precision,
    practitioner_id bigint NOT NULL,
    title character varying(255)
);


--
-- Name: devises_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.devises ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.devises_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.documents (
    id bigint NOT NULL,
    file_type character varying(255),
    filename character varying(255),
    path_or_url character varying(255),
    uploaded_at timestamp(6) without time zone,
    patient_id bigint,
    uploaded_by bigint,
    file_size_bytes bigint,
    title character varying(255)
);


--
-- Name: documents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.documents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employee_working_hours; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employee_working_hours (
    id bigint NOT NULL,
    day_of_week character varying(255),
    end_time time(6) without time zone,
    start_time time(6) without time zone,
    employee_id bigint NOT NULL,
    CONSTRAINT employee_working_hours_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: employee_working_hours_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employee_working_hours ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_working_hours_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: employees; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.employees (
    id bigint NOT NULL,
    address character varying(255),
    contract_type character varying(255),
    created_at timestamp(6) without time zone,
    date_of_birth date,
    email character varying(255),
    end_date date,
    first_name character varying(255),
    gender character varying(255),
    hire_date date,
    last_name character varying(255),
    national_id character varying(255),
    phone character varying(255),
    salary double precision,
    status character varying(255),
    updated_at timestamp(6) without time zone,
    dentist_id bigint,
    user_id bigint,
    CONSTRAINT employees_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'ON_LEAVE'::character varying])::text[])))
);


--
-- Name: employees_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.employees ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employees_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: expenses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    category character varying(255) NOT NULL,
    date date,
    description character varying(500),
    title character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    employee_id bigint,
    CONSTRAINT expenses_category_check CHECK (((category)::text = ANY ((ARRAY['OFFICE'::character varying, 'SUPPLIES'::character varying, 'UTILITIES'::character varying, 'SALARY'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: expenses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hand_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hand_payments (
    id bigint NOT NULL,
    amount integer,
    notes character varying(255),
    payment_date timestamp(6) without time zone,
    payment_method character varying(255),
    status character varying(255),
    plan_id bigint NOT NULL,
    user_id bigint NOT NULL,
    billing_cycle character varying(255),
    CONSTRAINT hand_payments_billing_cycle_check CHECK (((billing_cycle)::text = ANY ((ARRAY['MONTHLY'::character varying, 'YEARLY'::character varying])::text[])))
);


--
-- Name: hand_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.hand_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hand_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_defaults; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_defaults (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    default_price double precision NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    CONSTRAINT item_defaults_category_check CHECK (((category)::text = ANY ((ARRAY['CONSUMABLE'::character varying, 'TOOL'::character varying, 'PPE'::character varying, 'LAB_SUPPLIES'::character varying, 'MEDICATION'::character varying, 'IMAGING'::character varying, 'CLEANING'::character varying, 'OFFICE_SUPPLIES'::character varying])::text[])))
);


--
-- Name: item_defaults_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item_defaults ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_defaults_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.items (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expiry_date date,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    unit_price double precision NOT NULL,
    created_by bigint NOT NULL,
    item_default_id bigint NOT NULL
);


--
-- Name: items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: justification_contents; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.justification_contents (
    id bigint NOT NULL,
    content text NOT NULL,
    type character varying(255) NOT NULL,
    custom_type character varying(255),
    practitioner_id bigint NOT NULL,
    title character varying(150),
    CONSTRAINT justification_contents_type_check CHECK (((type)::text = ANY ((ARRAY['SCHOOL'::character varying, 'WORK'::character varying, 'SPORTS'::character varying, 'INSURANCE'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: justification_contents_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.justification_contents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.justification_contents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: justifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.justifications (
    id bigint NOT NULL,
    date timestamp(6) without time zone,
    final_content text NOT NULL,
    patient_id bigint NOT NULL,
    practitioner_id bigint NOT NULL,
    title character varying(150)
);


--
-- Name: justifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.justifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.justifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.laboratories (
    id bigint NOT NULL,
    address character varying(255),
    contact_person character varying(255),
    name character varying(255) NOT NULL,
    phone_number character varying(255),
    created_by bigint NOT NULL
);


--
-- Name: laboratories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.laboratories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: laboratory_payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.laboratory_payments (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    notes character varying(255),
    payment_date timestamp(6) without time zone NOT NULL,
    created_by bigint NOT NULL,
    laboratory_id bigint NOT NULL,
    CONSTRAINT laboratory_payments_amount_check CHECK ((amount >= (0)::double precision))
);


--
-- Name: laboratory_payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.laboratory_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.laboratory_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: materials; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.materials (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    created_by bigint NOT NULL
);


--
-- Name: materials_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.materials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.materials_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: medications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.medications (
    id bigint NOT NULL,
    description character varying(255),
    dosage_form character varying(255),
    name character varying(255),
    strength character varying(255),
    created_by bigint NOT NULL,
    generic_name character varying(255),
    CONSTRAINT medications_dosage_form_check CHECK (((dosage_form)::text = ANY ((ARRAY['TABLET'::character varying, 'CAPSULE'::character varying, 'SYRUP'::character varying, 'INJECTION'::character varying, 'OINTMENT'::character varying])::text[])))
);


--
-- Name: medications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.medications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.medications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: patients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.patients (
    id bigint NOT NULL,
    address character varying(255),
    age integer,
    created_at timestamp(6) without time zone,
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    phone character varying(255),
    created_by bigint,
    sex character varying(255),
    archived_at timestamp(6) without time zone
);


--
-- Name: patients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.patients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.patients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount double precision NOT NULL,
    date timestamp(6) without time zone NOT NULL,
    method character varying(255) NOT NULL,
    patient_id bigint NOT NULL,
    received_by bigint,
    CONSTRAINT payments_amount_check CHECK ((amount >= (0)::double precision)),
    CONSTRAINT payments_method_check CHECK (((method)::text = ANY ((ARRAY['CASH'::character varying, 'CARD'::character varying, 'BANK_TRANSFER'::character varying, 'CHECK'::character varying, 'OTHER'::character varying])::text[])))
);


--
-- Name: payments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: plans; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.plans (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(255) NOT NULL,
    duration_days integer,
    monthly_price integer,
    name character varying(255),
    yearly_monthly_price integer,
    max_dentists integer DEFAULT 1 NOT NULL,
    max_employees integer DEFAULT 0 NOT NULL,
    max_patients integer DEFAULT 0 NOT NULL,
    max_storage_gb double precision DEFAULT 0 NOT NULL
);


--
-- Name: plans_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescription_medications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prescription_medications (
    id bigint NOT NULL,
    amount character varying(255),
    duration character varying(255),
    frequency character varying(255),
    instructions character varying(255),
    name character varying(255),
    unit character varying(255),
    medication_id bigint NOT NULL,
    prescription_id bigint NOT NULL
);


--
-- Name: prescription_medications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prescription_medications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescription_medications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prescriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prescriptions (
    id bigint NOT NULL,
    date timestamp(6) without time zone,
    notes character varying(255),
    rx_id character varying(255) NOT NULL,
    patient_id bigint NOT NULL,
    practitioner_id bigint NOT NULL
);


--
-- Name: prescriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prescriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prescriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: protheses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.protheses (
    id bigint NOT NULL,
    date_created timestamp(6) without time zone,
    expected_return_date timestamp(6) without time zone,
    final_price double precision,
    lab_cost double precision,
    notes character varying(255),
    sent_to_lab_date timestamp(6) without time zone,
    status character varying(255),
    laboratory_id bigint,
    patient_id bigint,
    practitioner_id bigint,
    prothesis_catalog_id bigint,
    actual_return_date timestamp(6) without time zone,
    code character varying(255)
);


--
-- Name: protheses_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.protheses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.protheses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prothesis_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prothesis_catalog (
    id bigint NOT NULL,
    default_price double precision NOT NULL,
    is_flat_fee boolean NOT NULL,
    material character varying(255),
    name character varying(255) NOT NULL,
    created_by bigint NOT NULL,
    material_id bigint,
    default_lab_cost double precision DEFAULT 0 NOT NULL
);


--
-- Name: prothesis_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.prothesis_catalog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.prothesis_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: prothesis_teeth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.prothesis_teeth (
    prothesis_id bigint NOT NULL,
    tooth_number integer
);


--
-- Name: refresh_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.refresh_tokens (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone,
    revoked boolean NOT NULL,
    token character varying(255) NOT NULL,
    user_id bigint,
    ip_address character varying(100),
    last_used_at timestamp(6) without time zone,
    location character varying(120),
    user_agent character varying(255),
    device_id character varying(36)
);


--
-- Name: refresh_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.refresh_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.refresh_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: treatment_catalog; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.treatment_catalog (
    id bigint NOT NULL,
    code character varying(255),
    default_price double precision,
    description character varying(255),
    name character varying(255),
    created_by bigint NOT NULL,
    is_flat_fee boolean DEFAULT false NOT NULL
);


--
-- Name: treatment_catalog_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.treatment_catalog ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.treatment_catalog_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: treatment_teeth; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.treatment_teeth (
    treatment_id bigint NOT NULL,
    tooth_number integer
);


--
-- Name: treatments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.treatments (
    id bigint NOT NULL,
    date timestamp(6) without time zone,
    notes character varying(255),
    price double precision,
    patient_id bigint,
    practitioner_id bigint,
    treatment_catalog_id bigint,
    status character varying(255),
    updated_at timestamp(6) without time zone
);


--
-- Name: treatments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.treatments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.treatments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255),
    firstname character varying(255),
    lastname character varying(255),
    password_hash character varying(255),
    role character varying(255),
    username character varying(255) NOT NULL,
    phone_number character varying(20),
    is_email_verified boolean DEFAULT false,
    is_phone_verified boolean DEFAULT false,
    expiration_date timestamp(6) without time zone,
    plan_id bigint,
    plan_status character varying(255),
    can_delete_admin boolean DEFAULT false NOT NULL,
    address text,
    clinic_name character varying(255),
    phone_otp character varying(255),
    phone_otp_expires timestamp(6) without time zone,
    gestion_cabinet_pin_hash character varying(100),
    gestion_cabinet_pin_updated_at timestamp(6) without time zone,
    gestion_cabinet_pin_enabled boolean DEFAULT false NOT NULL,
    clinic_access_role character varying(255),
    owner_dentist_id bigint,
    time_format character varying(10),
    working_hours_end character varying(5),
    working_hours_mode character varying(20),
    working_hours_start character varying(5),
    date_format character varying(20),
    currency_label character varying(5),
    money_format character varying(20),
    password_reset_otp_last_sent_at timestamp(6) without time zone,
    phone_change_otp_last_sent_at timestamp(6) without time zone,
    phone_verification_otp_last_sent_at timestamp(6) without time zone,
    patient_cancelled_appointments_threshold integer,
    patient_money_owed_threshold double precision,
    CONSTRAINT users_clinic_access_role_check CHECK (((clinic_access_role)::text = ANY ((ARRAY['DENTIST'::character varying, 'PARTNER_DENTIST'::character varying, 'ASSISTANT'::character varying, 'RECEPTION'::character varying])::text[]))),
    CONSTRAINT users_plan_status_check CHECK (((plan_status)::text = ANY ((ARRAY['PENDING'::character varying, 'WAITING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['DENTIST'::character varying, 'ADMIN'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: appointments appointments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT appointments_pkey PRIMARY KEY (id);


--
-- Name: audit_logs audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);


--
-- Name: devise_items devise_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devise_items
    ADD CONSTRAINT devise_items_pkey PRIMARY KEY (id);


--
-- Name: devises devises_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devises
    ADD CONSTRAINT devises_pkey PRIMARY KEY (id);


--
-- Name: documents documents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT documents_pkey PRIMARY KEY (id);


--
-- Name: employee_working_hours employee_working_hours_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_working_hours
    ADD CONSTRAINT employee_working_hours_pkey PRIMARY KEY (id);


--
-- Name: employees employees_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT employees_pkey PRIMARY KEY (id);


--
-- Name: expenses expenses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);


--
-- Name: hand_payments hand_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hand_payments
    ADD CONSTRAINT hand_payments_pkey PRIMARY KEY (id);


--
-- Name: item_defaults item_defaults_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_defaults
    ADD CONSTRAINT item_defaults_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (id);


--
-- Name: justification_contents justification_contents_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justification_contents
    ADD CONSTRAINT justification_contents_pkey PRIMARY KEY (id);


--
-- Name: justifications justifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justifications
    ADD CONSTRAINT justifications_pkey PRIMARY KEY (id);


--
-- Name: laboratories laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_pkey PRIMARY KEY (id);


--
-- Name: laboratory_payments laboratory_payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratory_payments
    ADD CONSTRAINT laboratory_payments_pkey PRIMARY KEY (id);


--
-- Name: materials materials_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT materials_pkey PRIMARY KEY (id);


--
-- Name: medications medications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT medications_pkey PRIMARY KEY (id);


--
-- Name: patients patients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT patients_pkey PRIMARY KEY (id);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);


--
-- Name: plans plans_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);


--
-- Name: prescription_medications prescription_medications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescription_medications
    ADD CONSTRAINT prescription_medications_pkey PRIMARY KEY (id);


--
-- Name: prescriptions prescriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT prescriptions_pkey PRIMARY KEY (id);


--
-- Name: protheses protheses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protheses
    ADD CONSTRAINT protheses_pkey PRIMARY KEY (id);


--
-- Name: prothesis_catalog prothesis_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prothesis_catalog
    ADD CONSTRAINT prothesis_catalog_pkey PRIMARY KEY (id);


--
-- Name: refresh_tokens refresh_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);


--
-- Name: treatment_catalog treatment_catalog_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatment_catalog
    ADD CONSTRAINT treatment_catalog_pkey PRIMARY KEY (id);


--
-- Name: treatments treatments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatments
    ADD CONSTRAINT treatments_pkey PRIMARY KEY (id);


--
-- Name: justification_contents uk6h0vekt01vchg8x1ce9hpo657; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justification_contents
    ADD CONSTRAINT uk6h0vekt01vchg8x1ce9hpo657 UNIQUE (type, custom_type, practitioner_id);


--
-- Name: plans ukbsiq2g7uq9l49v27bsijicsys; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT ukbsiq2g7uq9l49v27bsijicsys UNIQUE (code);


--
-- Name: refresh_tokens ukghpmfn23vmxfu3spu3lfg4r2d; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);


--
-- Name: employees ukj2dmgsma6pont6kf7nic9elpd; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT ukj2dmgsma6pont6kf7nic9elpd UNIQUE (user_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: prescriptions ukrps2qc9gjabij6wmhfpl8k6s1; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT ukrps2qc9gjabij6wmhfpl8k6s1 UNIQUE (rx_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: idx_audit_logs_actor_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_actor_role ON public.audit_logs USING btree (actor_role);


--
-- Name: idx_audit_logs_actor_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_actor_user_id ON public.audit_logs USING btree (actor_user_id);


--
-- Name: idx_audit_logs_occurred_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_audit_logs_occurred_at ON public.audit_logs USING btree (occurred_at DESC);


--
-- Name: unique_non_other_per_practitioner; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX unique_non_other_per_practitioner ON public.justification_contents USING btree (type, practitioner_id) WHERE ((type)::text <> 'OTHER'::text);


--
-- Name: uq_justification_type_practitioner; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_justification_type_practitioner ON public.justification_contents USING btree (type, practitioner_id) WHERE ((type)::text <> 'OTHER'::text);


--
-- Name: employees fk1jq00f68l3mrbk9cxq9l1cnci; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk1jq00f68l3mrbk9cxq9l1cnci FOREIGN KEY (dentist_id) REFERENCES public.users(id);


--
-- Name: prothesis_teeth fk1l41iw2btfjw1hcs9id5kk86a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prothesis_teeth
    ADD CONSTRAINT fk1l41iw2btfjw1hcs9id5kk86a FOREIGN KEY (prothesis_id) REFERENCES public.protheses(id);


--
-- Name: refresh_tokens fk1lih5y2npsf8u5o3vhdb9y0os; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: documents fk1ugacya4ssi0ilf8a9tjycgs6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fk1ugacya4ssi0ilf8a9tjycgs6 FOREIGN KEY (uploaded_by) REFERENCES public.users(id);


--
-- Name: laboratory_payments fk2tc8l1pti9cu2tfplkve3fpxg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratory_payments
    ADD CONSTRAINT fk2tc8l1pti9cu2tfplkve3fpxg FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: protheses fk3luqdc9u8022n6hr0fr6lofjm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protheses
    ADD CONSTRAINT fk3luqdc9u8022n6hr0fr6lofjm FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id);


--
-- Name: devise_items fk3s3iwwx07wvns2wgh1whtamb8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devise_items
    ADD CONSTRAINT fk3s3iwwx07wvns2wgh1whtamb8 FOREIGN KEY (treatment_catalog_id) REFERENCES public.treatment_catalog(id);


--
-- Name: justification_contents fk4sv9f2u37pu0fqld1mc1bby23; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justification_contents
    ADD CONSTRAINT fk4sv9f2u37pu0fqld1mc1bby23 FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: patients fk5crb1l6i843y9oe9vneob0uj1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.patients
    ADD CONSTRAINT fk5crb1l6i843y9oe9vneob0uj1 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: employee_working_hours fk5hivng2t69s0dswh4e1f3l1l6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employee_working_hours
    ADD CONSTRAINT fk5hivng2t69s0dswh4e1f3l1l6 FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: payments fk5vwv4mwirmtu3lsjxlpc0dy02; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk5vwv4mwirmtu3lsjxlpc0dy02 FOREIGN KEY (received_by) REFERENCES public.users(id);


--
-- Name: item_defaults fk63iwyufk4rs15a28smth0nnv; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_defaults
    ADD CONSTRAINT fk63iwyufk4rs15a28smth0nnv FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: employees fk69x3vjuy1t5p18a5llb8h2fjx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.employees
    ADD CONSTRAINT fk69x3vjuy1t5p18a5llb8h2fjx FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: justifications fk76vvjm5dqj3ww6f1jpl6r18ox; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justifications
    ADD CONSTRAINT fk76vvjm5dqj3ww6f1jpl6r18ox FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: users fk7ivcvd1h71ojbel0mnkudkgdm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk7ivcvd1h71ojbel0mnkudkgdm FOREIGN KEY (owner_dentist_id) REFERENCES public.users(id);


--
-- Name: treatments fk8djm31y5jedj2s88odydl1mmw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatments
    ADD CONSTRAINT fk8djm31y5jedj2s88odydl1mmw FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: appointments fk8exap5wmg8kmb1g1rx3by21yt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fk8exap5wmg8kmb1g1rx3by21yt FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: items fk8on7qdb8vubhs6d33jmx6bp91; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT fk8on7qdb8vubhs6d33jmx6bp91 FOREIGN KEY (item_default_id) REFERENCES public.item_defaults(id);


--
-- Name: laboratories fk9sokvtcr56nmvimculuqmdiyp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT fk9sokvtcr56nmvimculuqmdiyp FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: devise_items fkaiiyxmgf6lv3y6ki1lvyk1a4a; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devise_items
    ADD CONSTRAINT fkaiiyxmgf6lv3y6ki1lvyk1a4a FOREIGN KEY (prothesis_catalog_id) REFERENCES public.prothesis_catalog(id);


--
-- Name: protheses fkbhwaiph0531qt0wyytmkrobdx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protheses
    ADD CONSTRAINT fkbhwaiph0531qt0wyytmkrobdx FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: hand_payments fkc72urdgo9dfiib8n7adkdlcaw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hand_payments
    ADD CONSTRAINT fkc72urdgo9dfiib8n7adkdlcaw FOREIGN KEY (plan_id) REFERENCES public.plans(id);


--
-- Name: prescription_medications fkcnibo4i1m6gwkeo4dylimfeg8; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescription_medications
    ADD CONSTRAINT fkcnibo4i1m6gwkeo4dylimfeg8 FOREIGN KEY (prescription_id) REFERENCES public.prescriptions(id);


--
-- Name: devises fkd794g096am0c04490nbelc4rx; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devises
    ADD CONSTRAINT fkd794g096am0c04490nbelc4rx FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: treatment_teeth fkeocjbw7q4p1ab54o6q3kxxyrp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatment_teeth
    ADD CONSTRAINT fkeocjbw7q4p1ab54o6q3kxxyrp FOREIGN KEY (treatment_id) REFERENCES public.treatments(id);


--
-- Name: prothesis_catalog fkgp8tieob762egrtv0bqbqa6q4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prothesis_catalog
    ADD CONSTRAINT fkgp8tieob762egrtv0bqbqa6q4 FOREIGN KEY (material_id) REFERENCES public.materials(id);


--
-- Name: hand_payments fkgr028tljdkt2mdq2tuhttc3ah; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hand_payments
    ADD CONSTRAINT fkgr028tljdkt2mdq2tuhttc3ah FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: protheses fkh6yaxecrucojmp5fxy1gmdg5c; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protheses
    ADD CONSTRAINT fkh6yaxecrucojmp5fxy1gmdg5c FOREIGN KEY (prothesis_catalog_id) REFERENCES public.prothesis_catalog(id);


--
-- Name: devise_items fkha6fetm3cyh52m5huer4aeb87; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devise_items
    ADD CONSTRAINT fkha6fetm3cyh52m5huer4aeb87 FOREIGN KEY (devise_id) REFERENCES public.devises(id);


--
-- Name: expenses fkheikgk1aaie0tpkmsodusmmrk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkheikgk1aaie0tpkmsodusmmrk FOREIGN KEY (employee_id) REFERENCES public.employees(id);


--
-- Name: users fki4ttvfkp7tl33d90ldkkagrxu; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fki4ttvfkp7tl33d90ldkkagrxu FOREIGN KEY (plan_id) REFERENCES public.plans(id);


--
-- Name: medications fkj3eykmor8aarm28inp05fvp79; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.medications
    ADD CONSTRAINT fkj3eykmor8aarm28inp05fvp79 FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: materials fkj3unvdjwlsccmqod6jl4w0vcp; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.materials
    ADD CONSTRAINT fkj3unvdjwlsccmqod6jl4w0vcp FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: treatment_catalog fkjmnva89c3m56w8fxb613wt0pm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatment_catalog
    ADD CONSTRAINT fkjmnva89c3m56w8fxb613wt0pm FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: treatments fkkedvl4seruued7q90x2f0gtth; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatments
    ADD CONSTRAINT fkkedvl4seruued7q90x2f0gtth FOREIGN KEY (treatment_catalog_id) REFERENCES public.treatment_catalog(id);


--
-- Name: laboratory_payments fkkieugf2slrhajhp75btrts8e0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratory_payments
    ADD CONSTRAINT fkkieugf2slrhajhp75btrts8e0 FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id);


--
-- Name: appointments fkkli1t8k603ra3uon20hoij3jt; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.appointments
    ADD CONSTRAINT fkkli1t8k603ra3uon20hoij3jt FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: expenses fkko0thccfpwh1bj150j3d4kq7m; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT fkko0thccfpwh1bj150j3d4kq7m FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: prothesis_catalog fkl0v7wx1nornx21lcuohykxtyi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prothesis_catalog
    ADD CONSTRAINT fkl0v7wx1nornx21lcuohykxtyi FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: payments fklvfcgbin5vh2ivae1l87bmawb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fklvfcgbin5vh2ivae1l87bmawb FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: prescriptions fkm6vuu1q95hfl1qf2w25lj74tf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT fkm6vuu1q95hfl1qf2w25lj74tf FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: prescription_medications fkn4tdfhfymiqhx8ft4usy31goi; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescription_medications
    ADD CONSTRAINT fkn4tdfhfymiqhx8ft4usy31goi FOREIGN KEY (medication_id) REFERENCES public.medications(id);


--
-- Name: prescriptions fkqydyol76jn1o37k1bdbkjgq74; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.prescriptions
    ADD CONSTRAINT fkqydyol76jn1o37k1bdbkjgq74 FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: justifications fkr1rhg8mr2fw715tps2ks0lneg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.justifications
    ADD CONSTRAINT fkr1rhg8mr2fw715tps2ks0lneg FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: devise_item_teeth fkse4itiiempt1cn2g2svpkbj5j; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.devise_item_teeth
    ADD CONSTRAINT fkse4itiiempt1cn2g2svpkbj5j FOREIGN KEY (devise_item_id) REFERENCES public.devise_items(id);


--
-- Name: protheses fkspwwnopim9bnaw95ibtwbnxfm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.protheses
    ADD CONSTRAINT fkspwwnopim9bnaw95ibtwbnxfm FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- Name: items fkstbwb3fvemcf9j1yf64fey29i; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT fkstbwb3fvemcf9j1yf64fey29i FOREIGN KEY (created_by) REFERENCES public.users(id);


--
-- Name: treatments fktmvudq7t9r2j7ov17x8cecqup; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.treatments
    ADD CONSTRAINT fktmvudq7t9r2j7ov17x8cecqup FOREIGN KEY (practitioner_id) REFERENCES public.users(id);


--
-- Name: documents fkuvd7wpcrgqmdwlxusy3ceunb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.documents
    ADD CONSTRAINT fkuvd7wpcrgqmdwlxusy3ceunb FOREIGN KEY (patient_id) REFERENCES public.patients(id);


--
-- PostgreSQL database dump complete
--
