-- Create fournisseurs table (supplier partners for inventory purchases)
CREATE TABLE IF NOT EXISTS public.fournisseurs (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    public_id uuid NOT NULL,
    name character varying(255) NOT NULL,
    contact_person text,
    phone_number text,
    address text,
    created_by bigint NOT NULL
);

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fournisseurs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT uk_fournisseurs_public_id UNIQUE (public_id);

ALTER TABLE ONLY public.fournisseurs
    ADD CONSTRAINT fk_fournisseurs_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);

-- Optional link from inventory items to fournisseurs
ALTER TABLE public.items
    ADD COLUMN IF NOT EXISTS fournisseur_id bigint;

ALTER TABLE ONLY public.items
    ADD CONSTRAINT fk_items_fournisseur_id FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseurs(id);
