-- Create fournisseur payments table (payments made to suppliers)
CREATE TABLE IF NOT EXISTS public.fournisseur_payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    amount double precision NOT NULL,
    payment_date timestamp without time zone NOT NULL,
    notes text,
    fournisseur_id bigint NOT NULL,
    created_by bigint NOT NULL
);

ALTER TABLE ONLY public.fournisseur_payments
    ADD CONSTRAINT fournisseur_payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fournisseur_payments
    ADD CONSTRAINT fk_fournisseur_payments_fournisseur_id FOREIGN KEY (fournisseur_id) REFERENCES public.fournisseurs(id);

ALTER TABLE ONLY public.fournisseur_payments
    ADD CONSTRAINT fk_fournisseur_payments_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);

