-- Create disease and allergy catalogs (per clinic owner).

CREATE TABLE IF NOT EXISTS public.disease_catalog (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_by bigint NOT NULL
);

ALTER TABLE ONLY public.disease_catalog
    ADD CONSTRAINT disease_catalog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.disease_catalog
    ADD CONSTRAINT fk_disease_catalog_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_disease_catalog_created_by_name_ci
    ON public.disease_catalog (created_by, lower(btrim(name)));


CREATE TABLE IF NOT EXISTS public.allergy_catalog (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name character varying(255) NOT NULL,
    description text,
    created_by bigint NOT NULL
);

ALTER TABLE ONLY public.allergy_catalog
    ADD CONSTRAINT allergy_catalog_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.allergy_catalog
    ADD CONSTRAINT fk_allergy_catalog_created_by FOREIGN KEY (created_by) REFERENCES public.users(id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_allergy_catalog_created_by_name_ci
    ON public.allergy_catalog (created_by, lower(btrim(name)));

