/* eslint-disable no-restricted-globals */
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";

// Precache all assets generated by VitePWA (InjectManifest strategy).
precacheAndRoute(self.__WB_MANIFEST || []);

// SPA navigation fallback.
const handler = createHandlerBoundToURL("/index.html");
registerRoute(new NavigationRoute(handler));

const normalizePayload = (event) => {
  try {
    const json = event?.data?.json?.();
    if (json && typeof json === "object") return json;
  } catch {
    // ignore
  }
  try {
    const text = event?.data?.text?.();
    if (!text) return null;
    return JSON.parse(text);
  } catch {
    return null;
  }
};

self.addEventListener("push", (event) => {
  const payload = normalizePayload(event) || {};
  const title = String(payload.title || "Cabinet+");
  const body = String(payload.body || "Vous avez une nouvelle notification.");
  const url = String(payload.url || "/");
  const threadId = payload.threadId != null ? String(payload.threadId) : null;

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      data: { url, threadId },
      badge: "/pwa-192.png",
      icon: "/pwa-192.png",
    })
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification?.close?.();
  const url = event?.notification?.data?.url || "/";

  event.waitUntil(
    (async () => {
      const allClients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of allClients) {
        try {
          const clientUrl = new URL(client.url);
          if (clientUrl.origin === self.location.origin) {
            await client.focus();
            client.postMessage({ type: "PUSH_OPEN", url });
            return;
          }
        } catch {
          // ignore
        }
      }
      await self.clients.openWindow(url);
    })()
  );
});

