/* eslint-disable no-restricted-globals */
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { registerRoute, NavigationRoute } from "workbox-routing";

// Precache all assets generated by VitePWA (InjectManifest strategy).
const manifest = self.__WB_MANIFEST || [];
precacheAndRoute(manifest);

// SPA navigation fallback.
const isPrecached = (url) => {
  const want = String(url || "");
  if (!want) return false;
  for (const entry of Array.isArray(manifest) ? manifest : []) {
    if (typeof entry === "string" && entry === want) return true;
    if (entry && typeof entry === "object" && String(entry.url || "") === want) return true;
  }
  return false;
};

// In dev, `__WB_MANIFEST` can be empty, and `createHandlerBoundToURL()` throws when the URL isn't precached.
// Fall back to network `index.html` so the SW doesn't crash.
const navHandler = isPrecached("/index.html")
  ? createHandlerBoundToURL("/index.html")
  : async () => fetch("/index.html", { cache: "no-store" });
registerRoute(new NavigationRoute(navHandler));

const normalizePayload = (event) => {
  try {
    const json = event?.data?.json?.();
    if (json && typeof json === "object") return json;
  } catch {
    // ignore
  }
  try {
    const text = event?.data?.text?.();
    if (!text) return null;
    return JSON.parse(text);
  } catch {
    return null;
  }
};

self.addEventListener("push", (event) => {
  const payload = normalizePayload(event) || {};
  const title = String(payload.title || "Cabinet+");
  const body = String(payload.body || "Vous avez une nouvelle notification.");
  const url = String(payload.url || "/");
  const threadId = payload.threadId != null ? String(payload.threadId) : null;

  event.waitUntil(
    self.registration.showNotification(title, {
      body,
      data: { url, threadId },
      badge: "/pwa-192.png",
      icon: "/pwa-192.png",
    })
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification?.close?.();
  const url = event?.notification?.data?.url || "/";

  event.waitUntil(
    (async () => {
      const allClients = await self.clients.matchAll({ type: "window", includeUncontrolled: true });
      for (const client of allClients) {
        try {
          const clientUrl = new URL(client.url);
          if (clientUrl.origin === self.location.origin) {
            await client.focus();
            client.postMessage({ type: "PUSH_OPEN", url });
            return;
          }
        } catch {
          // ignore
        }
      }
      await self.clients.openWindow(url);
    })()
  );
});
