package com.cabinetplus.backend.enums;

public enum AuditEventType {
    AUTH_LOGIN,
    AUTH_LOGOUT,
    AUTH_LOGOUT_ALL,
    AUTH_REGISTER,
    SECURITY_PIN_ENABLE,
    SECURITY_PIN_CHANGE,
    SECURITY_PIN_DISABLE,
    SECURITY_PIN_VERIFY,
    USER_ADMIN_CREATE,
    USER_DELETE,
    USER_PASSWORD_CHANGE,
    HAND_PAYMENT_CONFIRM,
    HAND_PAYMENT_REJECT
}
