package com.cabinetplus.backend.enums;

public enum NotificationType {
    MESSAGING_MESSAGE,
    SUPPORT_MESSAGE,
    ADMIN_GROUP_MESSAGE,

    PROTHESIS_STATUS_UPDATED,
    PROTHESIS_CANCELLATION_REQUESTED,
    PROTHESIS_CANCELLATION_DECIDED,

    LAB_PAYMENT_UPDATED,
    LAB_PAYMENT_CANCELLATION_REQUESTED,
    LAB_PAYMENT_CANCELLATION_DECIDED
}
